name: Python CI

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate Unit Test
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python3 hackathon/test.py

    - name: Run Unit Test
      id: unit-test
      run: |
        python3 unit_test_get_product_list.py > unit_test_output.txt 2>&1

    - name: Remove Unit Test File
      run: rm unit_test_get_product_list.py

    - name: Check Unit Test Output for Errors
      run: |
        if grep -q "Error" unit_test_output.txt; then
          echo "Error found in unit test output"
          exit 1
        else
          echo "Unit test passed"
        fi

#    - name: Generate documentation
#      run: python generate_doc.py main.py
